name = input("please enter your name")
age = input("please enter your age")
course =input("please enter your course")
contact = input("please enter your contact")
print("\n")
print("the name you had entered is",name)
print("the age you had entered is",age)
print("the course you had entered is",course)
print("the contact you had entered is",contact)
print("the above information you had entered is",true or false)
